services:
  ### Ubuntu ##################################
  ubuntu:
    image: ttungbmt/ubuntu
    build:
      context: ./ubuntu
      args:
        - UBUNTU_VERSION=${UBUNTU_VERSION}
        - TZ=${UBUNTU_TIMEZONE}
        - INSTALL_BAT=${UBUNTU_INSTALL_BAT}
        - INSTALL_FD=${UBUNTU_INSTALL_FD}
    tty: true

  ### Workspace Utilities ##################################
  workspace:
    image: ttungbmt/workspace
    build:
      context: ./workspace
      args:
        - UBUNTU_VERSION=${WORKSPACE_UBUNTU_VERSION}
        - http_proxy
        - https_proxy
        - no_proxy
    restart: unless-stopped
    privileged: true
    tty: true

  ### whoami ##############################################
  whoami:
    image: traefik/whoami
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=whoami.local
      - VIRTUAL_PORT=80
    networks:
      - default