volumes:
  userprofile:
    driver: ${VOLUMES_DRIVER}

networks:
  default:
  shared-proxy:
    driver: overlay
    external: true

services:
  ### Workspace Utilities ##################################
  workspace:
    image: ttungbmt/workspace
    restart: unless-stopped
    privileged: true
    working_dir: ${APP_CODE_PATH_CONTAINER}
    tty: true
    environment:
      - DOCKER_HOST=tcp://${DOCKER_HOST_IP}:${DOCKER_HOST_PORT}
      - DOCKER_TLS_VERIFY=
      - CHOKIDAR_USEPOLLING=true
      - GIT_USERNAME=${GIT_USERNAME}
      - GIT_EMAIL=${GIT_EMAIL}
    volumes:
      - userprofile:/home/ubuntu
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
    ports:
      - "${WORKSPACE_SSH_PORT}:22"
      - "${WORKSPACE_SUPERVISOR_PORT}:9001"
      - 8000
    networks:
      - shared-proxy
      - default

  ### nginx-proxy ##############################################
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - shared-proxy
      - default