volumes:
  userprofile:
    driver: ${VOLUMES_DRIVER}

networks:
  default:
  shared-proxy:
    driver: overlay
    external: true

services:
  ### Ubuntu ##################################
  ubuntu:
    image: ttungbmt/ubuntu
    build:
      context: ./ubuntu
      args:
        - UBUNTU_VERSION=${UBUNTU_VERSION}
        - TZ=${UBUNTU_TIMEZONE}
        - INSTALL_BAT=${UBUNTU_INSTALL_BAT}
        - INSTALL_FD=${UBUNTU_INSTALL_FD}
    tty: true

  ### Workspace Utilities ##################################
  workspace:
    image: ttungbmt/workspace
    build:
      context: ./workspace
      args:
        - UBUNTU_VERSION=${WORKSPACE_UBUNTU_VERSION}
        - http_proxy
        - https_proxy
        - no_proxy
    restart: unless-stopped
    privileged: true
    tty: true
    environment:
      - DOCKER_HOST=tcp://${DOCKER_HOST_IP}:${DOCKER_HOST_PORT}
      - DOCKER_TLS_VERIFY=
      - CHOKIDAR_USEPOLLING=true
      - GIT_USERNAME=${GIT_USERNAME}
      - GIT_EMAIL=${GIT_EMAIL}
    volumes:
      - userprofile:/home/ubuntu
    ports:
      - "${WORKSPACE_SSH_PORT}:22"
      - "${WORKSPACE_SUPERVISOR_PORT}:9001"
    networks:
      - shared-proxy
      - default

  ### nginx-proxy ##############################################
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - shared-proxy
      - default

  ### whoami ##############################################
  whoami:
    image: traefik/whoami
    expose:
      - "80"
    environment:
      - VIRTUAL_HOST=whoami.local
      - VIRTUAL_PORT=80
    networks:
      - default